apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticket-dev-392622/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticket-dev-392622/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticket-dev-392622/tickets
      context: tickets
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticket-dev-392622/orders
      context: orders
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticket-dev-392622/expiration
      context: expiration
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/ticket-dev-392622/payments
      context: payments
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticket-dev-392622
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}